name: tinyplayerss
description: Hello, My Name is Jaco but You can Call me tiny I am a Rumble Streamer and as a Streamer I need to Provide Educational Guides on how Rumble Streaming Works! So in this Article I'll be Providing You with Up to Date information about Rumble!
avatar: https://avatars.githubusercontent.com/u/123846642?v=4

footer-links:
  twitter: tinyplayerss
  youtube: channel/UCV2tbU7rb3tft2KvKSFEaXQ

url: https://tinyblogger.github.io
baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

paginate: 5
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  categories:
    output: true
